---
# tasks file for powertools

- name: enable powertools
  ini_file:
    path: /etc/yum.repos.d/CentOS-PowerTools.repo
    section: PowerTools
    option: enabled
    value: "1"
    mode: "0644"
  notify:
    - yum update cache
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version >= "8"
